blank_issues_enabled: false
contact_links:
  - name: Ask a question on the Discussion forum
    url: https://github.com/TownyAdvanced/Towny/discussions/new?category=Q-A
    about: Ask a question on the Discussion forum
