blank_issues_enabled: false
contact_links:
  - name: Đặt câu hỏi trên diễn đàn Thảo luận
    url: https://github.com/TownyAdvanced/Towny/discussions/new?category=Q-A
    about: Đặt câu hỏi trên diễn đàn Thảo luận
