name: Yêu cầu tính năng
description: Đề xuất ý tưởng cho server
title: 'Gợi ý: '
labels: [enhancement]
body:
    - type: textarea
      attributes:
          label: '**Vui lòng miêu tả thêm nhiều về tính năng mà bạn mong muốn:**'
      validations:
          required: true
