blank_issues_enabled: false
contact_links:
  - name: Đặt câu hỏi trên diễn đàn thảo luận
    url: https://github.com/tuanhp0/Uismine.vn/discussions/new?category=Q-A
    about: Đặt câu hỏi trên diễn đàn thảo luận
